# Generated by Django 4.1.6 on 2023-02-03 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("director", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=255)),
                (
                    "release_year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(2100),
                            django.core.validators.MinValueValidator(1900),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
